/**
 * In-memory seed data for the Admin Sales Pipeline + Installation Calendar.
 * Replaced by live `/sales` and `/installations` calls in the wiring pass.
 */
import {
  type PipelineSale,
  type Booking,
  bookingKey,
  ymd,
} from "./legacy-data";

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return ymd(d);
}

export function seedPipeline(): PipelineSale[] {
  return [
    {
      key: "c1_michael_brennan_0412345678",
      consultantId: "c1",
      consultantName: "James Carter",
      company: "Astra",
      companyType: "astra",
      firstName: "Michael",
      surname: "Brennan",
      phone: "0412 345 678",
      email: "m.brennan@example.com",
      address: "14 Sandy Bay Rd",
      suburb: "Sandy Bay",
      postcode: "7005",
      state: "TAS",
      leadGen: "Olivia M.",
      solar: "6.6kW",
      battery: "Tesla Powerwall 3",
      extrasTotal: 0,
      soldPrice: 18900,
      paymentMethod: "finance",
      systemType: "Solar + Battery",
      systemSize: "6.6",
      numPanels: "16",
      panelModel: "Jinko Tiger Neo 415W",
      inverterModel: "Fronius Primo 5.0",
      phase: "1-Phase",
      batteryModel: "Tesla Powerwall 3",
      hotWater: "Heat pump",
      switchboard: "Upgrade required",
      backup: "Whole home backup",
      roofType: "Colorbond",
      storeys: "Single",
      status: {
        openSolarId: "OS-44821",
        financeStatus: "finance_approved",
        adminStatus: "pre_approval_approved",
        meterChange: "completed",
        installation: "ready_to_book",
        installAdminStatus: "install_details_checked",
      },
    },
    {
      key: "c2_sarah_nguyen_0423111222",
      consultantId: "c2",
      consultantName: "Priya Sharma",
      company: "DC ELEC",
      companyType: "dcnt",
      firstName: "Sarah",
      surname: "Nguyen",
      phone: "0423 111 222",
      address: "8 Kingston View Dr",
      suburb: "Kingston",
      postcode: "7050",
      state: "TAS",
      leadGen: "Noah T.",
      solar: "10kW",
      battery: "",
      extrasTotal: 450,
      soldPrice: 11200,
      paymentMethod: "cash",
      systemType: "Solar Only",
      systemSize: "10",
      numPanels: "24",
      panelModel: "Trina Vertex S 425W",
      inverterModel: "Sungrow SG10RT",
      phase: "3-Phase",
      roofType: "Tile",
      storeys: "Double",
      status: {
        openSolarId: "OS-44890",
        adminStatus: "submitted",
        meterChange: "needs_submitting",
      },
    },
    {
      key: "c1_david_thompson_0433444555",
      consultantId: "c1",
      consultantName: "James Carter",
      company: "Astra",
      companyType: "astra",
      firstName: "David",
      surname: "Thompson",
      phone: "0433 444 555",
      address: "27 Goyder St",
      suburb: "Narrabundah",
      postcode: "2604",
      state: "ACT",
      leadGen: "Olivia M.",
      solar: "13.2kW",
      battery: "Sungrow SBR 12.8",
      extrasTotal: 0,
      soldPrice: 24500,
      paymentMethod: "finance",
      systemType: "Solar + Battery",
      systemSize: "13.2",
      numPanels: "32",
      panelModel: "Jinko Tiger Neo 415W",
      inverterModel: "Sungrow SH10RT",
      phase: "3-Phase",
      batteryModel: "Sungrow SBR 12.8",
      hotWater: "",
      roofType: "Tin",
      storeys: "Single",
      status: {
        openSolarId: "OS-45012",
        financeStatus: "finance_approved",
        adminStatus: "pre_approval_approved",
        meterChange: "completed",
        installation: "installation_booked",
        installAdminStatus: "stock_ordered",
        installDate: daysFromNow(3),
        installStatus: "installation_due",
      },
    },
    {
      key: "c3_emma_wilson_0444777888",
      consultantId: "c3",
      consultantName: "Liam O'Connor",
      company: "Astra",
      companyType: "astra",
      firstName: "Emma",
      surname: "Wilson",
      phone: "0444 777 888",
      address: "5 Antill St",
      suburb: "Dickson",
      postcode: "2602",
      state: "ACT",
      leadGen: "Sophia L.",
      solar: "6.6kW",
      battery: "",
      extrasTotal: 0,
      soldPrice: 8900,
      paymentMethod: "cash",
      systemType: "Solar Only",
      systemSize: "6.6",
      numPanels: "16",
      panelModel: "Aiko Neostar 440W",
      inverterModel: "GoodWe DNS 5kW",
      phase: "1-Phase",
      roofType: "Tile",
      storeys: "Single",
      status: {
        openSolarId: "OS-45120",
        adminStatus: "pre_approval_approved",
        meterChange: "not_required",
        installation: "ready_to_book",
      },
    },
    {
      key: "c2_robert_clarke_0455999000",
      consultantId: "c2",
      consultantName: "Priya Sharma",
      company: "DC ELEC",
      companyType: "dcnt",
      firstName: "Robert",
      surname: "Clarke",
      phone: "0455 999 000",
      address: "112 Maria St",
      suburb: "Tamworth",
      postcode: "2340",
      state: "NSW",
      leadGen: "Noah T.",
      solar: "8kW",
      battery: "BYD HVS 10.2",
      extrasTotal: 600,
      soldPrice: 19850,
      paymentMethod: "finance",
      systemType: "Solar + Battery",
      systemSize: "8",
      numPanels: "20",
      panelModel: "Trina Vertex S 425W",
      inverterModel: "Fronius Symo 8.2",
      phase: "3-Phase",
      batteryModel: "BYD HVS 10.2",
      hotWater: "Electric",
      roofType: "Colorbond",
      storeys: "Single",
      status: {
        openSolarId: "OS-45230",
        financeStatus: "finance_approved",
        adminStatus: "pre_approval_approved",
        meterChange: "completed",
        installation: "installation_booked",
        installAdminStatus: "install_details_checked",
        installDate: daysFromNow(1),
        installStatus: "installation_complete",
        finalisations: "cec_uploaded",
        paymentStatus: "full_payment_received",
      },
    },
    {
      key: "c4_jessica_lee_0466222333",
      consultantId: "c4",
      consultantName: "Hannah Reid",
      company: "Astra",
      companyType: "astra",
      firstName: "Jessica",
      surname: "Lee",
      phone: "0466 222 333",
      address: "19 Forster Cr",
      suburb: "Forrest",
      postcode: "2603",
      state: "ACT",
      leadGen: "Sophia L.",
      solar: "10kW",
      battery: "Tesla Powerwall 3",
      extrasTotal: 0,
      soldPrice: 21300,
      paymentMethod: "hesp",
      systemType: "Solar + Battery",
      systemSize: "10",
      numPanels: "24",
      panelModel: "Jinko Tiger Neo 440W",
      inverterModel: "Tesla Inverter",
      phase: "1-Phase",
      batteryModel: "Tesla Powerwall 3",
      roofType: "Tile",
      storeys: "Double",
      status: {
        financeStatus: "applied",
        adminStatus: "needs_applying",
      },
    },
    {
      key: "c3_andrew_walker_0477555666",
      consultantId: "c3",
      consultantName: "Liam O'Connor",
      company: "DC ELEC",
      companyType: "dcnt",
      firstName: "Andrew",
      surname: "Walker",
      phone: "0477 555 666",
      address: "44 Bay Rd",
      suburb: "Howrah",
      postcode: "7018",
      state: "TAS",
      leadGen: "Olivia M.",
      solar: "6.6kW",
      battery: "",
      extrasTotal: 0,
      soldPrice: 9600,
      paymentMethod: "cash",
      systemType: "Solar Only",
      systemSize: "6.6",
      numPanels: "16",
      panelModel: "Aiko Neostar 440W",
      inverterModel: "Sungrow SG5.0RS",
      phase: "1-Phase",
      roofType: "Tin",
      storeys: "Single",
      status: {
        adminStatus: "cancelled",
      },
    },
  ];
}

export function seedInstallations(): Record<string, Booking> {
  const store: Record<string, Booking> = {};
  // David Thompson — ACT, booked in 3 days, Dan AM
  const d1: Booking = {
    customerName: "David Thompson",
    phone: "0433 444 555",
    address: "27 Goyder St",
    suburb: "Narrabundah",
    postcode: "2604",
    consultant: "James Carter",
    systemType: "Solar + Battery",
    backup: "",
    systemSize: "13.2",
    numPanels: "32",
    panel: "Jinko Tiger Neo 415W",
    inverter: "Sungrow SH10RT",
    phases: "3-Phase",
    hotWater: "",
    battery: "Sungrow SBR 12.8",
    product: "13.2kW + Battery",
    roofType: "Tin",
    storey: "Single",
    switchboard: "",
    status: "booked",
    company: "astra",
    saleKey: "c1_david_thompson_0433444555",
    regionId: "act",
    date: daysFromNow(3),
    installerId: "dan",
    timeSlot: "am",
  };
  store[bookingKey(d1.regionId, d1.date, d1.installerId, d1.timeSlot)] = d1;

  // Robert Clarke — NSW, completed tomorrow, Charlie PM
  const d2: Booking = {
    customerName: "Robert Clarke",
    phone: "0455 999 000",
    address: "112 Maria St",
    suburb: "Tamworth",
    postcode: "2340",
    consultant: "Priya Sharma",
    systemType: "Solar + Battery",
    systemSize: "8",
    numPanels: "20",
    panel: "Trina Vertex S 425W",
    inverter: "Fronius Symo 8.2",
    phases: "3-Phase",
    hotWater: "Electric",
    battery: "BYD HVS 10.2",
    product: "8kW + Battery",
    roofType: "Colorbond",
    storey: "Single",
    status: "booked",
    company: "dcnt",
    saleKey: "c2_robert_clarke_0455999000",
    regionId: "nsw",
    date: daysFromNow(1),
    installerId: "charlie",
    timeSlot: "pm",
  };
  store[bookingKey(d2.regionId, d2.date, d2.installerId, d2.timeSlot)] = d2;

  // A needs-booking job — TAS South, Liam AM, in 2 days
  const d3: Booking = {
    customerName: "Karen Mills",
    phone: "0488 121 314",
    address: "9 Channel Hwy",
    suburb: "Taroona",
    postcode: "7053",
    consultant: "James Carter",
    systemType: "Solar Only",
    systemSize: "6.6",
    numPanels: "16",
    panel: "Jinko Tiger Neo 415W",
    inverter: "Fronius Primo 5.0",
    phases: "1-Phase",
    battery: "",
    product: "6.6kW",
    roofType: "Tile",
    storey: "Single",
    status: "needs_booking",
    company: "astra",
    regionId: "tas-south",
    date: daysFromNow(2),
    installerId: "liam",
    timeSlot: "am",
  };
  store[bookingKey(d3.regionId, d3.date, d3.installerId, d3.timeSlot)] = d3;

  return store;
}
